In [102]:
import pandas as pd
import requests

Check out for advaned stats explanations: 
https://www.nbastuffer.com/analytics-101/player-evaluation-metrics/ 

Just hovering over columns gives a nice explanation as well
https://www.nbastuffer.com/2020-2021-nba-player-stats/

Salary Cap Numbers
https://www.spotrac.com/nba/cba/

And example of the salary page I scraped
https://hoopshype.com/salaries/players/2020-2021/

In [103]:
player_stats_2021_url = 'https://www.nbastuffer.com/2021-2022-nba-player-stats/'

player_stats_urls = ["https://www.nbastuffer.com/2020-2021-nba-player-stats/", 
                        'https://www.nbastuffer.com/2019-2020-nba-player-stats/',
                        'https://www.nbastuffer.com/2018-2019-nba-player-stats/',
                        'https://www.nbastuffer.com/2017-2018-nba-player-stats/']

player_stats_urls2 = ["https://www.nbastuffer.com/2016-2017-nba-regular-season-player-stats/", 
                        'https://www.nbastuffer.com/2015-2016-nba-regular-season-player-stats/',
                        'https://www.nbastuffer.com/2014-2015-nba-regular-season-player-stats/',
                        'https://www.nbastuffer.com/2013-2014-nba-regular-season-player-stats/']                        

salary_cap_url = 'https://www.spotrac.com/nba/cba/'

player_salaries_urls = ['https://hoopshype.com/salaries/players/',
                    "https://hoopshype.com/salaries/players/2020-2021/", 
                    'https://hoopshype.com/salaries/players/2019-2020/',
                    'https://hoopshype.com/salaries/players/2018-2019/',
                    'https://hoopshype.com/salaries/players/2017-2018/',
                    'https://hoopshype.com/salaries/players/2016-2017/',
                    'https://hoopshype.com/salaries/players/2015-2016/',
                    'https://hoopshype.com/salaries/players/2014-2015/',
                    'https://hoopshype.com/salaries/players/2013-2014/']

# Player Stats

In [104]:
#Latest pages have two tables, need to grab only regular season
another_df_list = []

print(player_stats_2021_url)
r = requests.get(player_stats_2021_url)
df_list = pd.read_html(r.text) # this parses all the tables in webpages to a list
salaries_df = df_list[0] #no playoffs on this page, just current regular season
salaries_df.insert(1, 'Year', 2021 )
another_df_list.append(salaries_df)

for i, url in enumerate(player_stats_urls):
    print(url)
    r = requests.get(url)
    df_list = pd.read_html(r.text) # this parses all the tables in webpages to a list
    salaries_df = df_list[1] #this 1 grabs the second table on page - regular season, 0 would get playoffs
    salaries_df.insert(1, 'Year', 2020 - i)
    another_df_list.append(salaries_df)

https://www.nbastuffer.com/2021-2022-nba-player-stats/
https://www.nbastuffer.com/2020-2021-nba-player-stats/
https://www.nbastuffer.com/2019-2020-nba-player-stats/
https://www.nbastuffer.com/2018-2019-nba-player-stats/
https://www.nbastuffer.com/2017-2018-nba-player-stats/

In [105]:
stats_df = pd.concat(another_df_list)
stats_df

,RANK,Year,FULL NAME,TEAM,POS,AGE,GP,MPG,MIN%Minutes PercentagePercentage of team minutes used by a player while he was on the floor,"USG%Usage RateUsage rate, a.k.a., usage percentage is an estimate of the percentage of team plays used by a player while he was on the floor",...,APGAssistsAssists per game.,AST%Assist PercentageAssist percentage is an estimated percentage of teammate field goals a player assisted while the player is on the court,SPGStealsSteals per game.,BPGBlocksBlocks per game.,TOPGTurnoversTurnovers per game.,"VIVersatility IndexVersatility index is a metric that measures a playerâ€™s ability to produce in points, assists, and rebounds. The average player will score around a five on the index, while top players score above 10",ORTGOffensive RatingIndividual offensive rating is the number of points produced by a player per 100 total individual possessions.,DRTGDefensive RatingIndividual defensive rating estimates how many points the player allowed per 100 possessions he individually faced while staying on the court.,Tor%Turnover RateA metric that estimates the number of turnovers a player commits per 100 possessions,TOrTurnover RateA metric that estimates the number of turnovers a player commits per 100 possessions
0,NaN,2021,Precious Achiuwa,Tor,F,22.48,56,23.1,48.2,17.9,...,1.1,7.1,0.52,0.55,1.07,6.9,103.3,103.3,NaN,NaN
1,NaN,2021,Steven Adams,Mem,C,28.64,63,26.5,55.3,12.2,...,3.3,16.0,0.84,0.75,1.57,9.2,124.0,104.7,NaN,NaN
2,NaN,2021,Bam Adebayo,Mia,C-F,24.65,42,33.2,69.1,25.1,...,3.6,18.0,1.48,0.83,2.74,10.6,113.8,97.1,NaN,NaN
3,NaN,2021,Santi Aldama,Mem,F-C,21.16,27,10.2,21.4,17.1,...,0.5,6.7,0.07,0.26,0.33,6.2,98.6,104.6,NaN,NaN
4,NaN,2021,LaMarcus Aldridge,Bro,C-F,36.64,45,22.8,47.6,22.7,...,0.9,6.5,0.31,1.02,0.93,7.2,120.0,108.7,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,NaN,2017,Zach Collins,Por,C,20.00,66,15.8,33.0,15.4,...,0.8,7.1,0.26,0.47,0.89,5.7,92.6,96.1,NaN,0.161
601,NaN,2017,Zach LaVine,Chi,SG,22.00,24,27.3,57.0,29.5,...,3.0,18.6,1.00,0.17,1.79,8.6,99.2,105.1,NaN,0.097
602,NaN,2017,Zach Randolph,Sac,PF,36.00,59,25.6,53.2,27.6,...,2.2,14.9,0.71,0.17,1.97,9.3,101.6,105.0,NaN,0.125
603,NaN,2017,Zaza Pachulia,Gol,C,33.00,69,14.1,29.3,17.0,...,1.6,15.2,0.55,0.25,1.06,9.8,117.6,95.6,NaN,0.194
604,NaN,2017,Zhou Qi,Hou,PF,22.00,18,6.9,14.4,16.8,...,0.1,2.1,0.11,0.78,0.56,3.0,60.8,98.2,NaN,0.212

In [106]:
#Rename the mess that is these column names.  

stats_df_rename_dict = {'MIN%Minutes PercentagePercentage of team minutes used by a player while he was on the floor': 'MIN%',
       'USG%Usage RateUsage rate, a.k.a., usage percentage is an estimate of the percentage of team plays used by a player while he was on the floor': 'USG%',
       'TO%Turnover RateA metric that estimates the number of turnovers a player commits per 100 possessions': 'TO%',
       'eFG%Effective Shooting PercentageWith eFG%, three-point shots made are worth 50% more than two-point shots made. eFG% Formula=(FGM+ (0.5 x 3PM))/FGA' : 'eFG%',
       'TS%True Shooting PercentageTrue shooting percentage is a measure of shooting efficiency that takes into account field goals, 3-point field goals, and free throws.': 'TS%',
       'PPGPointsPoints per game.': 'PPG',
       'RPGReboundsRebounds per game.' : 'RPG',
       'TRB%Total Rebound PercentageTotal rebound percentage is estimated percentage of available rebounds grabbed by the player while the player is on the court.' : 'TRB%', 
       'APGAssistsAssists per game.' : 'APG',
       'AST%Assist PercentageAssist percentage is an estimated percentage of teammate field goals a player assisted while the player is on the court': 'AST%',
       'SPGStealsSteals per game.': 'SPG',
       'BPGBlocksBlocks per game.': 'BPG',
       'TOPGTurnoversTurnovers per game.': 'TOPG',
       'VIVersatility IndexVersatility index is a metric that measures a playerâ€™s ability to produce in points, assists, and rebounds. The average player will score around a five on the index, while top players score above 10': 'VI',
       'ORTGOffensive RatingIndividual offensive rating is the number of points produced by a player per 100 total individual possessions.': 'ORTG',
       'DRTGDefensive RatingIndividual defensive rating estimates how many points the player allowed per 100 possessions he individually faced while staying on the court.': 'DRTG',
       'Tor%Turnover RateA metric that estimates the number of turnovers a player commits per 100 possessions': 'Tor%',
       'TOrTurnover RateA metric that estimates the number of turnovers a player commits per 100 possessions': 'TOr'}

stats_df.rename(columns=stats_df_rename_dict, inplace=True)

In [107]:
stats_df

,RANK,Year,FULL NAME,TEAM,POS,AGE,GP,MPG,MIN%,USG%,...,APG,AST%,SPG,BPG,TOPG,VI,ORTG,DRTG,Tor%,TOr
0,NaN,2021,Precious Achiuwa,Tor,F,22.48,56,23.1,48.2,17.9,...,1.1,7.1,0.52,0.55,1.07,6.9,103.3,103.3,NaN,NaN
1,NaN,2021,Steven Adams,Mem,C,28.64,63,26.5,55.3,12.2,...,3.3,16.0,0.84,0.75,1.57,9.2,124.0,104.7,NaN,NaN
2,NaN,2021,Bam Adebayo,Mia,C-F,24.65,42,33.2,69.1,25.1,...,3.6,18.0,1.48,0.83,2.74,10.6,113.8,97.1,NaN,NaN
3,NaN,2021,Santi Aldama,Mem,F-C,21.16,27,10.2,21.4,17.1,...,0.5,6.7,0.07,0.26,0.33,6.2,98.6,104.6,NaN,NaN
4,NaN,2021,LaMarcus Aldridge,Bro,C-F,36.64,45,22.8,47.6,22.7,...,0.9,6.5,0.31,1.02,0.93,7.2,120.0,108.7,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,NaN,2017,Zach Collins,Por,C,20.00,66,15.8,33.0,15.4,...,0.8,7.1,0.26,0.47,0.89,5.7,92.6,96.1,NaN,0.161
601,NaN,2017,Zach LaVine,Chi,SG,22.00,24,27.3,57.0,29.5,...,3.0,18.6,1.00,0.17,1.79,8.6,99.2,105.1,NaN,0.097
602,NaN,2017,Zach Randolph,Sac,PF,36.00,59,25.6,53.2,27.6,...,2.2,14.9,0.71,0.17,1.97,9.3,101.6,105.0,NaN,0.125
603,NaN,2017,Zaza Pachulia,Gol,C,33.00,69,14.1,29.3,17.0,...,1.6,15.2,0.55,0.25,1.06,9.8,117.6,95.6,NaN,0.194
604,NaN,2017,Zhou Qi,Hou,PF,22.00,18,6.9,14.4,16.8,...,0.1,2.1,0.11,0.78,0.56,3.0,60.8,98.2,NaN,0.212

# Older Data
Doesn't have all advanced metrics.  Maybe better to not include?

In [108]:
another_df_list2 = []

for i, url in enumerate(player_stats_urls2):
    print(url)
    r = requests.get(url)
    df_list = pd.read_html(r.text) # this parses all the tables in webpages to a list
    salaries_df = df_list[0]
    salaries_df.columns = salaries_df.columns.droplevel(level = 0)
    salaries_df.insert(1, 'Year', 2016 - i)
    another_df_list2.append(salaries_df)

https://www.nbastuffer.com/2016-2017-nba-regular-season-player-stats/
https://www.nbastuffer.com/2015-2016-nba-regular-season-player-stats/
https://www.nbastuffer.com/2014-2015-nba-regular-season-player-stats/
https://www.nbastuffer.com/2013-2014-nba-regular-season-player-stats/

In [109]:
stats_df2 = pd.concat(another_df_list2)
stats_df2

,Rank,Year,PLAYER,TEAM,POS,AGE,GP,MPG,MIN%,USG%,...,TS%,PPG,RPG,TRB%,APG,AST%,SPG,BPG,VI,Unnamed: 25_level_1
0,NaN,2016,Aaron Brooks,Ind,PG,32,65,13.7,28.6,19.2,...,0.507,5.0,1.1,4.3,1.9,20.7,0.38,0.14,6.4,NaN
1,NaN,2016,Aaron Gordon,Orl,SF,21,80,28.7,59.8,20.1,...,0.530,12.7,5.1,9.6,1.9,10.5,0.81,0.50,6.9,NaN
2,NaN,2016,Adreian Payne,Min,PF,25,18,7.5,15.7,23.0,...,0.505,3.5,1.8,14.2,0.4,8.0,0.44,0.39,7.3,NaN
3,NaN,2016,AJ Hammons,Dal,C,24,22,7.4,15.5,17.6,...,0.472,2.2,1.7,13.2,0.2,3.8,0.05,0.59,4.9,NaN
4,NaN,2016,Al Horford,Bos,C,30,68,32.3,67.2,19.7,...,0.553,14.0,6.8,11.8,5.0,24.4,0.76,1.26,9.7,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
509,NaN,2013,Tony Wroten,Phi,SG,20,72,24.3,50.2,27.9,...,0.493,13.0,3.2,7.0,3.0,21.2,1.08,0.22,8.2,NaN
510,NaN,2013,Nick Young,Lal,SG,28,64,28.1,58.3,27.0,...,0.564,17.9,2.6,4.9,1.5,9.1,0.73,0.19,5.9,NaN
511,NaN,2013,Thaddeus Young,Phi,PF,25,79,34.2,70.6,24.3,...,0.512,17.9,6.0,9.5,2.3,11.9,2.13,0.46,7.3,NaN
512,NaN,2013,Cody Zeller,Cha,C,21,82,17.1,35.2,19.1,...,0.498,6.0,4.3,14.2,1.1,10.5,0.49,0.50,7.1,NaN
513,NaN,2013,Tyler Zeller,Cle,C,24,70,14.8,30.3,17.4,...,0.581,5.7,4.0,15.2,0.5,5.5,0.26,0.54,6.1,NaN

In [110]:
#Need to relabel a few of the columns
old_stats_rename_dict = {'PLAYER':'FULL NAME',
                        'Rank':'RANK'}

stats_df2.rename(columns=old_stats_rename_dict, inplace=True)

#Convert Turn over percentage to match new data which is turnovers over 100 possessions
#stats_df2['TO%'] = stats_df2['TO%'] * 100

In [111]:
total_stats_df = pd.concat([stats_df, stats_df2])

In [112]:
#Convert Turn over percentage to match new data which is turnovers over 100 possessions
total_stats_df['TOr'] = total_stats_df['TOr'] * 100

#Combine the 3 turnover per 100 game columns into one

total_stats_df['TO_100_Games'] = total_stats_df['TO%'].combine_first(total_stats_df['Tor%'].combine_first(total_stats_df['TOr']))

In [113]:
#Drop the extra turnover columns
total_stats_df.drop(['TOr', 'Tor%', 'TO%', 'TOPG'], axis = 1, inplace=True)

In [114]:
#Check out NA Values
total_stats_df.isna().sum(axis=0).sort_values(ascending = False)[0:10]

RANK                   5199
Unnamed: 25_level_1    5199
ORTG                   2238
DRTG                   2232
eFG%                   2094
TS%                      32
TO_100_Games             30
AGE                       1
MPG                       0
RPG                       0
dtype: int64

In [115]:
#Drop the columns shown
total_stats_df.drop(['RANK', 'Unnamed: 25_level_1'], axis = 1, inplace=True)

In [116]:
#Fill in advanced stats

#Effective Field Goal Percentage Formula=[(All Field Goals Made) + 0.5*(3P Field Goals Made)]/(All Field Goal Attempts)
efg_idx = total_stats_df['eFG%'].isna()

total_stats_df['eFG%'] = (total_stats_df['2PA'] * total_stats_df['2P%'] + 
                        0.5 * (total_stats_df['3PA'] * total_stats_df['3P%'])) / \
                        (total_stats_df['2PA'] + total_stats_df['3PA'])

#nan values are people with no shots.  0% eFG%
total_stats_df['eFG%'].fillna(0, inplace = True)                      

#nan values are people with no turnovers
total_stats_df['TO_100_Games'].fillna(0, inplace = True)   

#nan values are people with no shots
total_stats_df['TS%'].fillna(0, inplace = True)   

total_stats_df['AGE'].fillna(28, inplace = True)

In [117]:
total_stats_df.isna().sum(axis=0).sort_values(ascending = False)[0:3]

ORTG    2238
DRTG    2232
Year       0
dtype: int64

In [118]:
total_stats_df.to_csv('data/stats_only-2013-2021.csv', index = False)

# Salaries

In [124]:
another_df_list = []

year_strings = ['2021/22', '2020/21', '2019/20', '2018/19', '2017/18', '2016/17', '2015/16', '2014/15', '2013/14'] #used to consolidate salaries into one column

for i, url in enumerate(player_salaries_urls):
    print(url)
    r = requests.get(url)
    df_list = pd.read_html(r.text) # this parses all the tables in webpages to a list
    salaries_df = df_list[0]
    salaries_df.insert(1, 'Year', 2021 - i)
    salaries_df['Salary'] = salaries_df[year_strings[i]]
    another_df_list.append(salaries_df)

https://hoopshype.com/salaries/players/
https://hoopshype.com/salaries/players/2020-2021/
https://hoopshype.com/salaries/players/2019-2020/
https://hoopshype.com/salaries/players/2018-2019/
https://hoopshype.com/salaries/players/2017-2018/
https://hoopshype.com/salaries/players/2016-2017/
https://hoopshype.com/salaries/players/2015-2016/
https://hoopshype.com/salaries/players/2014-2015/
https://hoopshype.com/salaries/players/2013-2014/

In [125]:
salaries_df = pd.concat(another_df_list)

#drop the extra columns
salaries_df = salaries_df[['Player', 'Year', 'Salary']]

#Clean up the $ signs and commas, change type to int
salaries_df['Salary'] = salaries_df['Salary'].str.replace("[^0-9.]", '').astype(int)
salaries_df.reset_index(drop=True, inplace=True)
salaries_df

C:\Users\davek\AppData\Local\Temp/ipykernel_17596/42587525.py:7: FutureWarning: The default value of regex will change from True to False in a future version.
  salaries_df['Salary'] = salaries_df['Salary'].str.replace("[^0-9.]", '').astype(int)

                   Player  Year    Salary
0           Stephen Curry  2021  45780966
1               John Wall  2021  44310840
2            James Harden  2021  44310840
3       Russell Westbrook  2021  44211146
4            Kevin Durant  2021  42018900
...                   ...   ...       ...
4948  Darius Johnson-Odom  2013     46404
4949          Vander Blue  2013     28834
4950        Shane Edwards  2013     28834
4951        Tony Mitchell  2013     28834
4952          DJ Stephens  2013     28834

[4953 rows x 3 columns]

In [126]:
salaries_df.to_csv('data/salaries_only.csv', index = False)

# Salary Cap

In [127]:
r = requests.get(salary_cap_url)
df_list = pd.read_html(r.text) # this parses all the tables in webpages to a list
salary_cap_df = df_list[0]

#remove $ and commas
salary_cap_df['Cap Maximum'] = salary_cap_df['Cap Maximum'].str.replace("[^0-9.]", '').astype(int)

salary_cap_df.head()

C:\Users\davek\AppData\Local\Temp/ipykernel_17596/3778360174.py:6: FutureWarning: The default value of regex will change from True to False in a future version.
  salary_cap_df['Cap Maximum'] = salary_cap_df['Cap Maximum'].str.replace("[^0-9.]", '').astype(int)

,Year,Cap Maximum,Cap $ +/-,Cap % +/-,Highest Team Cap,Lowest Team Cap,Highest Player Cap
0,2021,112414000,"$3,274,000",3.00%,"Golden State Warriors $184,024,769","Oklahoma City Thunder $90,342,857","Stephen Curry $45,780,966"
1,2020,109140000,$0,0.00%,"Golden State Warriors $175,825,052","New York Knicks $101,969,879","Stephen Curry $43,006,362"
2,2019,109140000,"$7,271,000",7.14%,"Houston Rockets $151,594,903","New York Knicks $110,055,762","Stephen Curry $40,231,758"
3,2018,101869000,"$2,776,000",2.80%,"Golden State Warriors $154,587,831","Dallas Mavericks $87,760,060","Stephen Curry $37,457,154"
4,2017,99093000,"$4,950,000",5.26%,"Cleveland Cavaliers $140,394,596","Chicago Bulls $90,105,625","Stephen Curry $34,682,550"

In [128]:
salary_cap_df.to_csv('data/salary_cap.csv', index = False)

# Merge Large Dataset

In [129]:
#Merge Stats and Salary
merged_df = total_stats_df.merge(salaries_df, how = 'left', left_on = ['FULL NAME', 'Year'], right_on=['Player', 'Year'])
merged_df.drop('Player', axis = 1, inplace=True)

In [130]:
#Merge Stats, Salary, and Salary Cap
merged_df = merged_df.merge(salary_cap_df[['Year', 'Cap Maximum']], how = 'left', on = 'Year')

#Add Players % of Cap
merged_df['Salary%OfCap'] = round(merged_df['Salary'] / merged_df['Cap Maximum'], 4)

In [131]:
#Missing Salary Data
print('Players with no Salary Data:', merged_df['Salary'].isna().sum())

#Drop those rows
merged_df = merged_df[merged_df['Salary'].notna()]
print('Dropped')

Players with no Salary Data: 438
Dropped

In [132]:
#Traded Players - show up as two rows with different stats for both teams.  What to do?  Drop?  Keep most games played?
#for now included, will revisit
dupes = merged_df.groupby(['FULL NAME', 'Year']).size()

print('Traded Players Over Dataset:', dupes[dupes > 1].size)

Traded Players Over Dataset: 514

# Deal with traded players showing up in multiple rows.

# Export and Import Check

In [550]:
merged_df.to_csv('data/NBA_Player_Dataset-2013-2021.csv', index = False)

In [551]:
new_dataset = pd.read_csv('data/NBA_Player_Dataset-2013-2021.csv')
new_dataset

,Year,FULL NAME,TEAM,POS,AGE,GP,MPG,MIN%,USG%,TO%,...,AST%,SPG,BPG,TOPG,VI,ORTG,DRTG,Salary,Cap Maximum,Salary%OfCap
0,2021,Precious Achiuwa,Tor,F,22.48,56,23.1,48.2,17.9,11.1,...,7.1,0.52,0.55,1.07,6.9,103.3,103.3,2711280.0,112414000,0.0241
1,2021,Steven Adams,Mem,C,28.64,63,26.5,55.3,12.2,20.0,...,16.0,0.84,0.75,1.57,9.2,124.0,104.7,17073171.0,112414000,0.1519
2,2021,Bam Adebayo,Mia,C-F,24.65,42,33.2,69.1,25.1,14.6,...,18.0,1.48,0.83,2.74,10.6,113.8,97.1,28103500.0,112414000,0.2500
3,2021,LaMarcus Aldridge,Bro,C-F,36.64,45,22.8,47.6,22.7,7.8,...,6.5,0.31,1.02,0.93,7.2,120.0,108.7,2641691.0,112414000,0.0235
4,2021,Nickeil Alexander-Walker,Nor,G,23.52,50,26.3,54.9,24.9,11.2,...,16.4,0.82,0.38,1.70,7.5,96.4,109.6,3261480.0,112414000,0.0290
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4756,2013,Tony Wroten,Phi,SG,20.00,72,24.3,50.2,27.9,17.7,...,21.2,1.08,0.22,NaN,8.2,NaN,NaN,1160040.0,58679000,0.0198
4757,2013,Nick Young,Lal,SG,28.00,64,28.1,58.3,27.0,8.6,...,9.1,0.73,0.19,NaN,5.9,NaN,NaN,1106942.0,58679000,0.0189
4758,2013,Thaddeus Young,Phi,PF,25.00,79,34.2,70.6,24.3,10.7,...,11.9,2.13,0.46,NaN,7.3,NaN,NaN,8600000.0,58679000,0.1466
4759,2013,Cody Zeller,Cha,C,21.00,82,17.1,35.2,19.1,15.0,...,10.5,0.49,0.50,NaN,7.1,NaN,NaN,3857040.0,58679000,0.0657
4760,2013,Tyler Zeller,Cle,C,24.00,70,14.8,30.3,17.4,14.9,...,5.5,0.26,0.54,NaN,6.1,NaN,NaN,1633440.0,58679000,0.0278